### ISSUE TITLE
git permission errors

### ISSUE THREAD

**Issue by DamienIrving** [aus-ref-clim-data-nci/GPCC#1]
I'm getting permission errors when trying to `git pull` at `/g/data/ia39/gpcc/replica/code`.
```
error: cannot open .git/FETCH_HEAD: Permission denied
```
[This page](https://techoverflow.net/2019/05/07/how-to-fix-git-error-cannot-open-git-fetch_head-permission-denied/) suggests the problem is that I'm not the owner of that directory...

**Comment by paolap** [comment]
I changed the permissions so now group should be able to write the files.

**Comment by DamienIrving** [comment]
Thanks, @paolap!
